### PR TITLE
install Singular using apt-get

### PR DESCRIPTION
**Pull request by heiderich**

### CODE REVIEW

**Comment by heiderich** [comment]
I am surprised that Travis failed for c6d78cc, since it was working at least for Julia 1.1 under Linux in a previous build:

https://travis-ci.org/heiderich/HomalgProject.jl/builds/555013405

Anyway I tried to add OS X support by installing Singular using Homebrew in 
01c2506. The installation seems to be successful. The build however does not reach the tests, because of the following error, which I think is independent.

`No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.`

**Comment by mohamed-barakat** [comment]
Thank you very much @heiderich for the PR. And yes, I think it is a matter of luck if compiling GAP passes or not. Travis does not like that everything is written by `julia` in `build.log` as it does not detect any progress during the installation procedure. This explanation is due to @fingolfin, I hope I am quoting him correctly.

**Comment by heiderich** [comment]
@mohamed-barakat I added two commits that make travis more patient. I hope this will work for now. If not, we will probably just have to increase the number of minutes travis will wait. The Mac OS X builds seem to be much slower.

**Comment by mohamed-barakat** [comment]
@heiderich: Works, thank you very much 👍 

As a side effect the documentation has been built:

https://homalg-project.github.io/HomalgProject.jl/dev/

**Pull request merged**
